In [1]:
import pandas as pd
import lxml

In [6]:
tables = pd.read_html('https://nuforc.org/webreports/ndxlCT.html')

In [7]:
len(tables)

1

In [9]:
df = tables[0]

In [10]:
df

,Date / Time,City,State,Country,Shape,Duration,Summary,Posted,Images
0,7/24/23 20:02,Enfield,CT,USA,Formation,Approx 60 seconds,3 craft in formation,7/29/23,Yes
1,7/23/23 10:45,New Haven,CT,USA,Rectangle,aprox 2 minutes,"Object moved in straight line, ""disappearing,""...",7/29/23,NaN
2,7/14/23 21:00,New haven,CT,USA,Rectangle,2 minutes,Looked out window saw ufo it appeared to fly b...,7/29/23,NaN
3,7/14/23 05:00,Fairfield,CT,USA,Orb,5 seconds,Traveling orb plus a star,7/29/23,NaN
4,7/13/23 20:21,North haven,CT,USA,Cigar,30 seconds,The craft was white almost like a tic tac that...,7/29/23,NaN
...,...,...,...,...,...,...,...,...,...
1977,2/3/51 22:00,Thompsonville,CT,USA,Disk,30 seconds,"A golden-orange glowing bowl, flat on top, 2 f...",7/25/04,NaN
1978,6/4/49 10:00,Los Angeles,CT,USA,Circle,10 minutes,Six objects seen by many over Los Angeles in 1949,9/2/05,NaN
1979,22:00,Stratford,CT,USA,Unknown,8 to 10,Observed 2 large white lights that appeared to...,6/8/12,NaN
1980,01/23/20×0 20:00,Tolland,CT,USA,Other,5-7 seconds,I was driving when i saw blue lights that look...,1/31/20,NaN
1981,1980's 17:00,Danbury,CT,USA,Oval,5 min,I was driving south on rt 7 in Danbury when I ...,3/2/21,NaN